### ISSUE TITLE
problem installing in Bookworm

### ISSUE THREAD

**Issue by namllihs** [orionrobots/python_usb_robot_arm#16]
Hi I have this working well with a Pi4 and a Pi Zero2 W, with Buster. However on trying out the new Bookworm OS the installer fails  when it gets to:
pip3 install git+https://github.com/orionrobots/python_usb_robot_arm

I was running it in a virtual environment.

Any ideas on how to get around this?

TIA,
  Steve.

**Comment by dannystaple** [comment]
Hello, can you show me the output you get when you try this please?

**Comment by namllihs** [comment]
Hi Danny,

       the two pip commands seem to work and then it fails.

python3-libusb1 is already the newest version (2.0.1-0.1).
python3-pip is already the newest version (23.0.1+dfsg-1+rpt1).
git is already the newest version (1:2.39.2-1.1).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.


Cheers,
  Steve.

**Comment by namllihs** [comment]
Hi Danny,

           I got round the problem by manually running the pip commands and then manually editing the rules file.
I then got this error when importing the usb_arm library.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/steve/usb_arm.py", line 4, in <module>
    import usb.core
ModuleNotFoundError: No module named ‘usb'

So I manually installed the usb library and now everything seems to be working OK.

Cheers,

  Steve.

**Comment by dannystaple** [comment]
Ok - had some time to test all this (And have a working robot arm again, having damaged one during a move).
I've found a couple of problems:
- Related to what you've seen, I'll need to reconsider the installation post pep-688.  The shell script might only go as far as system packages, then you willbe informated that you need to pip install into your own python environment (eg a project venv).
- The internal package name relative to setup py is also wrong now - I must have moved the folder. I'll need to rename that back. 

This likely needs a new package version, and may need modern packaging (pyproject.toml, uv or poetry compatible).

**Comment by namllihs** [comment]
Thanks for the update

**Comment by dannystaple** [comment]
I've addressed the internal name while fixing the tests up again, they'd been dead for ages. I've renamed that to `owi_maplin_usb_arm` instead of the somewhat generic `usb_arm` or `usb_robot_arm`. This still doesn't address the pep-688 problem with the install script yet.
